### ISSUE TITLE
Question on lost pages

### ISSUE THREAD

**Issue by manuelsilverio** [vcokltfre/tutorial-v2#2]
In your tutorials, you used to have a section for error handling which was magnificent. It used to be here: https://tutorial.vcokltfre.dev/tutorial/12-errors/ 

Is it possible to get this back online?

**Comment by vcokltfre** [comment]
Yeah I'm working to get all the content back, but the issue is most is built around discord.py 1.7 which means it's no longer too relevant to the Discord development ecosystem, so I'm also needing to update it to use newer things like interactions. Ill be working on transferring everything over in the coming weeks but I felt like I couldn't keep using the old one anymore because it was so outdated

**Comment by manuelsilverio** [comment]
Ok, thanks for the update
